export var Products = [
    {
        id: 1,
        name:'Cabage Salad',
        price:4.99,
        quantity:'250g',
        rating:'4.2',
        isLike:false,
        url:"./cabbage.png",
        color:'#ffedff',
        Quantity: 1,
    },
    {
        id: 2,
        name:'Noodle salad',
        price:6.30,
        quantity:'300g',
        rating:'4.5',
        isLike:false,
        url:"./noodle.png",
        color:'#ffe9e3',
        Quantity: 1,
    },
    {
        id: 3,
        name:'Vegitable mix',
        price:5.99,
        quantity:'400g',
        rating:'5.0',
        isLike:true,
        url:"./VegMix.png",
        color:'#e3f6f5',
        Quantity: 1,
    },
    {
        id: 4,
        name:'Seafood soup',
        price:6.10,
        quantity:'350g',
        rating:'4.4',
        isLike:true,
        url:"./seafood.png",
        color:'#d5def5',
        Quantity: 1,
    },
    {
        id: 5,
        name:'Bean soup',
        price:4.40,
        quantity:'350g',
        rating:'4.9',
        isLike:true,
        url:"./beanSoup.png",
        color:'#9bf4d5',
        Quantity: 1,
    },
    {
        id: 6,
        name:'Stewed vegitables',
        price:4.99,
        quantity:'400g',
        rating:'3.9',
        isLike:false,
        url:"./stewed.png",
        color:'#a5bdfd',
        Quantity: 1,
    },
    {
        id: 7,
        name:'Chicken soup',
        price:3.99,
        quantity:'250g',
        rating:'4.2',
        isLike:true,
        url:"./Chicken.png",
        color:'#ffebeb',
        Quantity: 1,
    },
    {
        id: 8,
        name:'Roast potatoes',
        price:4.99,
        quantity:'300g',
        rating:'4.4',
        isLike:false,
        url:"./Roast.png",
        color:'#feffdf',
        Quantity: 1,
    },
]